# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 10

init:
  - git config --global core.autocrlf false

environment:
  matrix:
    # node.js
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 8

install:
  - ps: Install-Product node $env:nodejs_version
  - IF %nodejs_version% LSS 7 npm -g install npm@5
  - npm install --ignore-scripts

build: off

test_script:
  - node --version && npm --version
  - npm test

matrix:
  fast_finish: false

# cache:
#   - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json     # npm cache
#   - node_modules -> package.json                                    # local npm modules
