[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.99"
swc_atoms = "7.0.0"
swc_compiler_base = "32.0.0"
swc_config = "3.1.1"
swc_common = { version = "14.0.3", features = ["parking_lot"] }
swc_ecma_ast = "15.0.0"
swc_ecma_parser = "23.0.0"
parking_lot = "0.12.4"
