[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.98"
swc_atoms = "5.0.0"
swc_compiler_base = "18.0.0"
swc_common = { version = "8.1.0", features = ["parking_lot"] }
swc_ecma_ast = "8.1.2"
swc_ecma_parser = "11.1.2"
parking_lot = "0.12.3"
