[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
swc_atoms = "0.6.0"
swc_compiler_base = "0.3.18"
swc_common = { version = "0.33.2", features = ["ahash", "parking_lot"] }
swc_ecma_ast = "0.110.2"
swc_ecma_parser = "0.141.5"
swc_error_reporters = "0.17.2"
parking_lot = "0.12.1"
swc_ecma_lints = "0.89.10"
swc_ecma_transforms_base = "0.134.10"
swc_ecma_visit = "0.96.2"
