[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
swc_atoms = "0.6.7"
swc_compiler_base = "0.9.0"
swc_common = { version = "0.33.26", features = ["ahash", "parking_lot"] }
swc_ecma_ast = "0.113.5"
swc_ecma_parser = "0.144.1"
parking_lot = "0.12.3"
