[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.95"
swc_atoms = "3.1.0"
swc_compiler_base = "11.0.0"
swc_common = { version = "6.1.0", features = ["parking_lot"] }
swc_ecma_ast = "6.1.0"
swc_ecma_parser = "8.0.1"
parking_lot = "0.12.3"
