[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
swc_atoms = "0.6.7"
swc_compiler_base = "0.15.2"
swc_common = { version = "0.36.3", features = ["ahash", "parking_lot"] }
swc_ecma_ast = "0.117.4"
swc_ecma_parser = "0.148.3"
parking_lot = "0.12.3"
