[package]
name = "parse_ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
swc_atoms = "0.6.5"
swc_compiler_base = "0.4.18"
swc_common = { version = "0.33.12", features = ["ahash", "parking_lot"] }
swc_ecma_ast = "0.110.17"
swc_ecma_parser = "0.141.37"
parking_lot = "0.12.1"
