version: 2

unit_tests: &unit_tests
  steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: Run unit tests.
        command: npm run ci:test

jobs:
  analysis:
    docker:
      - image: rollupcabal/circleci-node-base:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci --ignore-scripts
      - run:
          name: Run linting.
          command: npm run lint
      - run:
          name: Run NPM Security Audit
          command: npm run security
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  node-v6-latest:
    docker:
      - image: rollupcabal/circleci-node-v6:latest
    <<: *unit_tests
  node-v8-latest:
    docker:
      - image: rollupcabal/circleci-node-v8:latest
    <<: *unit_tests
  node-v10-latest:
    docker:
      - image: rollupcabal/circleci-node-v10:latest
    <<: *unit_tests

workflows:
  version: 2
  validate-test:
    jobs:
      - analysis:
          filters:
            tags:
              only: /.*/
      - node-v6-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
      - node-v8-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
      - node-v10-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
