version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  analysis:
    docker:
      - image: rollupcabal/circleci-node-base:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm ci --ignore-scripts
      - run:
          name: Running linting
          command: npm run ci:lint
      - run:
          name: Running NPM Security Audit
          command: npm run security
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  node-v10-latest:
    docker:
      - image: rollupcabal/circleci-node-v10:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Running tests
          command: npm run ci:test
  node-v12-latest:
    docker:
      - image: rollupcabal/circleci-node-v12:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Running tests
          command: npm run ci:test:only
      - store_artifacts:
          name: Storing browser build for REPL
          path: /home/circleci/project/dist/rollup.browser.js
          destination: rollup.browser.js
      - run:
          name: Post REPL comment
          command: ./scripts/post-comment.js
  node-v14-latest:
    docker:
      - image: rollupcabal/circleci-node-v14:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Running tests with coverage
          command: npm run ci:coverage
  windows-v10-latest:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - run:
          name: Configure git line breaks
          command: git config --global core.autocrlf false
      - checkout
      - run:
          name: Select Node 10
          command: nvm install 10 && nvm use 10
      - run:
          name: Installing Dependencies
          command: npm ci
      - run:
          name: Running tests
          command: npm test
  windows-v14-latest:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - run:
          name: Configure git line breaks
          command: git config --global core.autocrlf false
      - checkout
      - run:
          name: Select Node 14
          command: nvm install 14 && nvm use 14
      - run:
          name: Installing Dependencies
          command: npm ci
      - run:
          name: Running tests
          command: npm test

workflows:
  version: 2
  validate-test:
    jobs:
      - analysis:
          filters:
            tags:
              only: /.*/
      - node-v10-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
      - node-v12-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
      - node-v14-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
      - windows-v10-latest:
          filters:
            tags:
              only: /.*/
      - windows-v14-latest:
          filters:
            tags:
              only: /.*/
